// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ChatMessage.proto
// Protobuf Java Version: 4.27.1

package com.yen.model.proto;

public final class ChatMessageProto {
  private ChatMessageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      ChatMessageProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>int64 fromUserId = 1;</code>
     * @return The fromUserId.
     */
    long getFromUserId();

    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>int64 toUserId = 2;</code>
     * @return The toUserId.
     */
    long getToUserId();

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 发送时间,格式(yyyy-MM-dd HH:mm:ss）
     * </pre>
     *
     * <code>string sendTime = 4;</code>
     * @return The sendTime.
     */
    java.lang.String getSendTime();
    /**
     * <pre>
     * 发送时间,格式(yyyy-MM-dd HH:mm:ss）
     * </pre>
     *
     * <code>string sendTime = 4;</code>
     * @return The bytes for sendTime.
     */
    com.google.protobuf.ByteString
        getSendTimeBytes();

    /**
     * <pre>
     * 消息类型(0建立连接|1文本消息|2图片消息|3文件消息|4语音消息|5视频消息|6广告消息)
     * </pre>
     *
     * <code>int32 type = 5;</code>
     * @return The type.
     */
    int getType();

    /**
     * <pre>
     * 状态(0已发送|1已读|2发送失败|3已撤回)
     * </pre>
     *
     * <code>int32 status = 6;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <pre>
     * 消息唯一标识符(数据库自增生成)
     * </pre>
     *
     * <code>int64 id = 7;</code>
     * @return The id.
     */
    long getId();
  }
  /**
   * <pre>
   * 数据交流对象(内部类)
   * </pre>
   *
   * Protobuf type {@code ChatMessage}
   */
  public static final class ChatMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ChatMessage)
      ChatMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        ChatMessage.class.getName());
    }
    // Use ChatMessage.newBuilder() to construct.
    private ChatMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ChatMessage() {
      content_ = "";
      sendTime_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yen.model.proto.ChatMessageProto.internal_static_ChatMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yen.model.proto.ChatMessageProto.internal_static_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yen.model.proto.ChatMessageProto.ChatMessage.class, com.yen.model.proto.ChatMessageProto.ChatMessage.Builder.class);
    }

    public static final int FROMUSERID_FIELD_NUMBER = 1;
    private long fromUserId_ = 0L;
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>int64 fromUserId = 1;</code>
     * @return The fromUserId.
     */
    @java.lang.Override
    public long getFromUserId() {
      return fromUserId_;
    }

    public static final int TOUSERID_FIELD_NUMBER = 2;
    private long toUserId_ = 0L;
    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>int64 toUserId = 2;</code>
     * @return The toUserId.
     */
    @java.lang.Override
    public long getToUserId() {
      return toUserId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object content_ = "";
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTIME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sendTime_ = "";
    /**
     * <pre>
     * 发送时间,格式(yyyy-MM-dd HH:mm:ss）
     * </pre>
     *
     * <code>string sendTime = 4;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public java.lang.String getSendTime() {
      java.lang.Object ref = sendTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sendTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送时间,格式(yyyy-MM-dd HH:mm:ss）
     * </pre>
     *
     * <code>string sendTime = 4;</code>
     * @return The bytes for sendTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSendTimeBytes() {
      java.lang.Object ref = sendTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sendTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_ = 0;
    /**
     * <pre>
     * 消息类型(0建立连接|1文本消息|2图片消息|3文件消息|4语音消息|5视频消息|6广告消息)
     * </pre>
     *
     * <code>int32 type = 5;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int STATUS_FIELD_NUMBER = 6;
    private int status_ = 0;
    /**
     * <pre>
     * 状态(0已发送|1已读|2发送失败|3已撤回)
     * </pre>
     *
     * <code>int32 status = 6;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    public static final int ID_FIELD_NUMBER = 7;
    private long id_ = 0L;
    /**
     * <pre>
     * 消息唯一标识符(数据库自增生成)
     * </pre>
     *
     * <code>int64 id = 7;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fromUserId_ != 0L) {
        output.writeInt64(1, fromUserId_);
      }
      if (toUserId_ != 0L) {
        output.writeInt64(2, toUserId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, content_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sendTime_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, sendTime_);
      }
      if (type_ != 0) {
        output.writeInt32(5, type_);
      }
      if (status_ != 0) {
        output.writeInt32(6, status_);
      }
      if (id_ != 0L) {
        output.writeInt64(7, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fromUserId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, fromUserId_);
      }
      if (toUserId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, toUserId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, content_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sendTime_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, sendTime_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, type_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, status_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yen.model.proto.ChatMessageProto.ChatMessage)) {
        return super.equals(obj);
      }
      com.yen.model.proto.ChatMessageProto.ChatMessage other = (com.yen.model.proto.ChatMessageProto.ChatMessage) obj;

      if (getFromUserId()
          != other.getFromUserId()) return false;
      if (getToUserId()
          != other.getToUserId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getSendTime()
          .equals(other.getSendTime())) return false;
      if (getType()
          != other.getType()) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (getId()
          != other.getId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROMUSERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFromUserId());
      hash = (37 * hash) + TOUSERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getToUserId());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getSendTime().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yen.model.proto.ChatMessageProto.ChatMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yen.model.proto.ChatMessageProto.ChatMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yen.model.proto.ChatMessageProto.ChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yen.model.proto.ChatMessageProto.ChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yen.model.proto.ChatMessageProto.ChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yen.model.proto.ChatMessageProto.ChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yen.model.proto.ChatMessageProto.ChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.yen.model.proto.ChatMessageProto.ChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.yen.model.proto.ChatMessageProto.ChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.yen.model.proto.ChatMessageProto.ChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yen.model.proto.ChatMessageProto.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.yen.model.proto.ChatMessageProto.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yen.model.proto.ChatMessageProto.ChatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 数据交流对象(内部类)
     * </pre>
     *
     * Protobuf type {@code ChatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatMessage)
        com.yen.model.proto.ChatMessageProto.ChatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yen.model.proto.ChatMessageProto.internal_static_ChatMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yen.model.proto.ChatMessageProto.internal_static_ChatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yen.model.proto.ChatMessageProto.ChatMessage.class, com.yen.model.proto.ChatMessageProto.ChatMessage.Builder.class);
      }

      // Construct using com.yen.model.proto.ChatMessageProto.ChatMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fromUserId_ = 0L;
        toUserId_ = 0L;
        content_ = "";
        sendTime_ = "";
        type_ = 0;
        status_ = 0;
        id_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yen.model.proto.ChatMessageProto.internal_static_ChatMessage_descriptor;
      }

      @java.lang.Override
      public com.yen.model.proto.ChatMessageProto.ChatMessage getDefaultInstanceForType() {
        return com.yen.model.proto.ChatMessageProto.ChatMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.yen.model.proto.ChatMessageProto.ChatMessage build() {
        com.yen.model.proto.ChatMessageProto.ChatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yen.model.proto.ChatMessageProto.ChatMessage buildPartial() {
        com.yen.model.proto.ChatMessageProto.ChatMessage result = new com.yen.model.proto.ChatMessageProto.ChatMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.yen.model.proto.ChatMessageProto.ChatMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fromUserId_ = fromUserId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.toUserId_ = toUserId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.sendTime_ = sendTime_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yen.model.proto.ChatMessageProto.ChatMessage) {
          return mergeFrom((com.yen.model.proto.ChatMessageProto.ChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yen.model.proto.ChatMessageProto.ChatMessage other) {
        if (other == com.yen.model.proto.ChatMessageProto.ChatMessage.getDefaultInstance()) return this;
        if (other.getFromUserId() != 0L) {
          setFromUserId(other.getFromUserId());
        }
        if (other.getToUserId() != 0L) {
          setToUserId(other.getToUserId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getSendTime().isEmpty()) {
          sendTime_ = other.sendTime_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                fromUserId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                toUserId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                sendTime_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                type_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                status_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long fromUserId_ ;
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>int64 fromUserId = 1;</code>
       * @return The fromUserId.
       */
      @java.lang.Override
      public long getFromUserId() {
        return fromUserId_;
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>int64 fromUserId = 1;</code>
       * @param value The fromUserId to set.
       * @return This builder for chaining.
       */
      public Builder setFromUserId(long value) {

        fromUserId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>int64 fromUserId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromUserId_ = 0L;
        onChanged();
        return this;
      }

      private long toUserId_ ;
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>int64 toUserId = 2;</code>
       * @return The toUserId.
       */
      @java.lang.Override
      public long getToUserId() {
        return toUserId_;
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>int64 toUserId = 2;</code>
       * @param value The toUserId to set.
       * @return This builder for chaining.
       */
      public Builder setToUserId(long value) {

        toUserId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>int64 toUserId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toUserId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object sendTime_ = "";
      /**
       * <pre>
       * 发送时间,格式(yyyy-MM-dd HH:mm:ss）
       * </pre>
       *
       * <code>string sendTime = 4;</code>
       * @return The sendTime.
       */
      public java.lang.String getSendTime() {
        java.lang.Object ref = sendTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sendTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 发送时间,格式(yyyy-MM-dd HH:mm:ss）
       * </pre>
       *
       * <code>string sendTime = 4;</code>
       * @return The bytes for sendTime.
       */
      public com.google.protobuf.ByteString
          getSendTimeBytes() {
        java.lang.Object ref = sendTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sendTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送时间,格式(yyyy-MM-dd HH:mm:ss）
       * </pre>
       *
       * <code>string sendTime = 4;</code>
       * @param value The sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTime(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sendTime_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送时间,格式(yyyy-MM-dd HH:mm:ss）
       * </pre>
       *
       * <code>string sendTime = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendTime() {
        sendTime_ = getDefaultInstance().getSendTime();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送时间,格式(yyyy-MM-dd HH:mm:ss）
       * </pre>
       *
       * <code>string sendTime = 4;</code>
       * @param value The bytes for sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sendTime_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 消息类型(0建立连接|1文本消息|2图片消息|3文件消息|4语音消息|5视频消息|6广告消息)
       * </pre>
       *
       * <code>int32 type = 5;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 消息类型(0建立连接|1文本消息|2图片消息|3文件消息|4语音消息|5视频消息|6广告消息)
       * </pre>
       *
       * <code>int32 type = 5;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {

        type_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型(0建立连接|1文本消息|2图片消息|3文件消息|4语音消息|5视频消息|6广告消息)
       * </pre>
       *
       * <code>int32 type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <pre>
       * 状态(0已发送|1已读|2发送失败|3已撤回)
       * </pre>
       *
       * <code>int32 status = 6;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       * 状态(0已发送|1已读|2发送失败|3已撤回)
       * </pre>
       *
       * <code>int32 status = 6;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {

        status_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态(0已发送|1已读|2发送失败|3已撤回)
       * </pre>
       *
       * <code>int32 status = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = 0;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       * 消息唯一标识符(数据库自增生成)
       * </pre>
       *
       * <code>int64 id = 7;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * 消息唯一标识符(数据库自增生成)
       * </pre>
       *
       * <code>int64 id = 7;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息唯一标识符(数据库自增生成)
       * </pre>
       *
       * <code>int64 id = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        id_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ChatMessage)
    }

    // @@protoc_insertion_point(class_scope:ChatMessage)
    private static final com.yen.model.proto.ChatMessageProto.ChatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yen.model.proto.ChatMessageProto.ChatMessage();
    }

    public static com.yen.model.proto.ChatMessageProto.ChatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMessage>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
      @java.lang.Override
      public ChatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChatMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yen.model.proto.ChatMessageProto.ChatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ChatMessage.proto\"\200\001\n\013ChatMessage\022\022\n\nf" +
      "romUserId\030\001 \001(\003\022\020\n\010toUserId\030\002 \001(\003\022\017\n\007con" +
      "tent\030\003 \001(\t\022\020\n\010sendTime\030\004 \001(\t\022\014\n\004type\030\005 \001" +
      "(\005\022\016\n\006status\030\006 \001(\005\022\n\n\002id\030\007 \001(\003B\'\n\023com.ye" +
      "n.model.protoB\020ChatMessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ChatMessage_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserId", "Content", "SendTime", "Type", "Status", "Id", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
